[default]
cell_size = 180

[default.ql]
learning_rate = 0.1
discount_factor = 0.9
epsilon_start = 0.3
epsilon_decay = 0.999
num_episodes = 100
max_steps_per_episode = 1000
actions = ["forward", "turn_left", "turn_right"]

[default.evolution]
input_size = 8
hidden_size = 16
output_size = 3
max_steps = 50

[default.sensor.tof]
step_size = 0.5
max_distance = 2000 # bigger than max(cell_size * width, cell_size * height)
offset_angle = 30

[default.logging]
level = "INFO"

[default.typer]
enable_pretty_exception = true
show_pretty_exception_local = false

[development]

[development.logging]
level = "DEBUG"
